import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import { motion } from "framer-motion";
import { Helmet } from "react-helmet";
import html2pdf from "html2pdf.js/dist/html2pdf.bundle";

export default function BikeStatus() {
  const [latestReservation, setLatestReservation] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("http://localhost:5000/api/reservations")
      .then((res) => res.json())
      .then((data) => {
        if (data.length > 0) {
          setLatestReservation(data[0]);
        }
        setLoading(false);
      })
      .catch((err) => {
        console.error("Error al cargar reservas:", err);
        setLoading(false);
      });
  }, []);

  const handleDownload = () => {
    if (!latestReservation) return;

    const content = `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px; color: #333;">
        <h2 style="color: #2b6cb0; margin-bottom: 20px;">🛠️ BikeDrop Appointment Summary</h2>
        <table style="width: 100%; border-collapse: collapse;">
          <tbody>
            <tr><td style="padding: 8px;"><strong>Status:</strong></td><td>Booked</td></tr>
            <tr><td style="padding: 8px;"><strong>Name:</strong></td><td>${latestReservation.name}</td></tr>
            <tr><td style="padding: 8px;"><strong>Email:</strong></td><td>${latestReservation.email}</td></tr>
            <tr><td style="padding: 8px;"><strong>Phone:</strong></td><td>${latestReservation.phone}</td></tr>
            <tr><td style="padding: 8px;"><strong>Address:</strong></td><td>${latestReservation.address}, Floor ${latestReservation.floor}, ${latestReservation.city} - ${latestReservation.postalCode}</td></tr>
            <tr><td style="padding: 8px;"><strong>Date:</strong></td><td>${new Date(latestReservation.date).toLocaleDateString("en-GB")}</td></tr>
            <tr><td style="padding: 8px;"><strong>Time:</strong></td><td>${latestReservation.time}</td></tr>
            <tr><td style="padding: 8px;"><strong>Plan:</strong></td><td>${latestReservation.service}</td></tr>
            ${
              latestReservation.note
                ? `<tr><td style="padding: 8px;"><strong>Note:</strong></td><td>${latestReservation.note}</td></tr>`
                : ""
            }
          </tbody>
        </table>
        <p style="margin-top: 30px; font-size: 12px; color: #555;">
          Generated by BikeDrop.dk — ${new Date().toLocaleString()}
        </p>
      </div>
    `;

    const opt = {
      margin: 0.5,
      filename: "BikeDrop-Appointment.pdf",
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
    };

    html2pdf().set(opt).from(content).save();
  };

  return (
    <>
      <Helmet>
        <title>BikeDrop | Status</title>
      </Helmet>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 30 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="min-h-screen bg-blue-50"
      >
        <Navbar />

        <div className="p-6 flex flex-col items-center justify-start text-center">
          <h2 className="text-xl font-semibold mb-4">Bike Status</h2>

          <div
            className="bg-white p-6 rounded-xl shadow-md w-full max-w-sm space-y-3 text-left text-sm text-gray-700"
          >
            {loading ? (
              <p className="text-gray-500 text-center">Loading...</p>
            ) : latestReservation ? (
              <>
                <p><strong>Status:</strong> Booked</p>
                <p><strong>Name:</strong> {latestReservation.name}</p>
                <p><strong>Email:</strong> {latestReservation.email}</p>
                <p><strong>Phone:</strong> {latestReservation.phone}</p>
                <p>
                  <strong>Address:</strong> {latestReservation.address}, Floor {latestReservation.floor}, {latestReservation.city} - {latestReservation.postalCode}
                </p>
                <p>
                  <strong>Date:</strong>{" "}
                  {new Date(latestReservation.date).toLocaleDateString("es-AR")}
                </p>
                <p><strong>Time:</strong> {latestReservation.time}</p>
                <p><strong>Plan:</strong> {latestReservation.service}</p>
                {latestReservation.note && (
                  <p><strong>Note:</strong> {latestReservation.note}</p>
                )}
              </>
            ) : (
              <p className="text-gray-500 text-center">No bookings yet.</p>
            )}
          </div>

          {latestReservation && (
            <button
              onClick={handleDownload}
              className="mt-4 bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 text-sm"
            >
              Download PDF
            </button>
          )}

          <Link
            to="/main"
            className="mt-6 inline-block text-blue-600 hover:underline text-sm"
          >
            ← Back to BikeDropPage
          </Link>
        </div>
      </motion.div>
    </>
  );
}
